### PR TITLE
Change the HostedZoneId type, now it autoselects in the UI.

### PR DESCRIPTION
**Pull request by robertmassaioli**
Sorry about all of the whitespace changes...not sure what caused that.

### CODE REVIEW

**Comment by m-chandler** [comment]
Thanks!

**Comment by cj-zeiger** [comment]
@m-chandler I think this might have broken the create stack flow.

I'm getting `Parameter validation failed: parameter value for parameter name HostedZoneId does not exist. Rollback requested by user.` when trying to make a new stack without using the DNS options.

Edit: I just tried to create a new stack with the version just before this change and it worked.

**Comment by m-chandler** [comment]
@cj-zeiger Ah yeah so it did. I thought it did the paramter validation on the parameters page, sadly also failed when I went to create the stack. Have reverted. Thanks for raising this!

**Comment by robertmassaioli** [comment]
Sorry all! I think the problem is that I left the default to be the empty string. Gonna test a fix soon.

**Comment by m-chandler** [comment]
Thanks, I didn't have time to tinker much before work.

**Comment by robertmassaioli** [comment]
Screenshot 2024-10-22 at 9 56 11 am

I've confirmed the bad behaviour. Yeesh. And it does not even complain in the selection screens!!

**Comment by robertmassaioli** [comment]
Okay, even removing the default empty string did not work. Giving up on this change for now.

**Pull request merged**
