### PR TITLE
Use ipv6 to avoid public ipv4 address charges

### PR DESCRIPTION
**Pull request by robinld**
Untested but I think this is directionally right
Stacked on #24

### CODE REVIEW

**Comment by m-chandler** [comment]
Thanks for this one too @robinld. I'm unfortunately no longer across all these AWS changes. If it's untested, I might just give it a deploy over the weekend to be sure before merging.

**Comment by robinld** [comment]
Turns out this doesn’t work cuz m3.medium doesn’t support ipv6. I tried some other instance types, like c6gd, but I couldn’t get it to work with ECS. It wasn’t recognizing it as a “container instance”. I thought putting that ecs ami on it would be enough for it to be a container host.

**Comment by robertmassaioli** [comment]
@robinld given that nobody should be using m3.medium anymore can we get this merged in? 

See: https://github.com/m-chandler/factorio-spot-pricing/issues/32

Does this work with m6a.large for example?

**Comment by m-chandler** [comment]
I can't get this working. It needed a few tweaks I've pushed in https://github.com/m-chandler/factorio-spot-pricing/commit/58e39a1bf217d41296da972cf58b84648b09eb05, yet now I'm faced with this error

image

The ECS CLI reports there are no missing attributes. I don't know 

```
> ecs-cli-windows-amd64-latest.exe check-attributes --cluster f-24-3-cluster --container-instances c94fa58bc8064897b265f10df74008d9 --task-def f-24-3-EcsTask-XwctExdf7RqB --region ap-southeast-2
Container Instance  Missing Attributes
f-24-3-cluster      None
```

EDIT: Maybe I'm an idiot, trying something...

**Comment by m-chandler** [comment]
Ok, got it deployed - was missing a subnet in the ECS::Service definition.

Seems like my home router might not support IPv6 out of the box, or maybe my ISP doesn't. So I can't reach IPv6 only sites. Apparently IPv6 adoption is only 50%?

Since we'd have to retain the IPv4 address for compatibility, adding IPv6 doesn't provide much value.

Saving $0.005/hr is nice, but having 100% of users be able to use this template is nicer haha!

Closing this PR as I don't think this is something we can merge yet.

Happy to be corrected?

**Comment by robertmassaioli** [comment]
I agree with that assessment but I would say that we should set a calendar reminder for a year for now to see if support has improved. Thanks for looking into it!

**Pull request closed without merging**
