### PR TITLE
Making space age be an option for the template. (#40)

### PR DESCRIPTION
**Pull request by robertmassaioli**
I've set it to false by default because everybody that has Factorio can work with the false setting but only Space Age players can use the true setting.

### CODE REVIEW

**Comment by robertmassaioli** [comment]
@m-chandler you are probably on vacation or somethnig but, if other people test this branch, please give it a thumbs up so that they know it's good when they get back.

**Comment by m-chandler** [comment]
@robertmassaioli Nah just working... playing Factorio 😂.
I made one comment, and have found that backslash indeed should not be there. Template won't deploy with it there. Testing rest of it now...

**Comment by m-chandler** [comment]
@robertmassaioli Yep looks good, thanks. That backslash just needs to go. Remove and I will approve/merge.

**Comment by robertmassaioli** [comment]
Oops, done. That's what I get for moving too quickly.

**Pull request merged**
