### PR TITLE
Multi Server Stacks

### PR DESCRIPTION
**Pull request by robertmassaioli**
In this Pull request, I have parameterised all of the templates so that you can have more than one server per stack.

I have also written a script to make it really easy to replace the save on a particular server.

Please let me know what you think of this.

I've left the 1-server template behind which is the template that currently exists but have tweaked it so that it works with the autogenerated shell script for easy control.

What do you think? I'm raising this now for early feedback.

### CODE REVIEW

**Comment by m-chandler** [comment]
I appreciate the effort, but I'm not sure this is something I want to merge in.

I'm trying to keep the template simple and maintainable. With this change, something like updating Launch Configuration to Launch Templates becomes increasibly painful, as there's multiple references within multiple templates to update. Yes, the multi-server templates could be generated by code instead, but then I come back to trying to keep the template simple and maintainable.

I'm not convinced that deploying multiple servers is a common use case, so I'm wary of introducing a lot of complexity and maintenance burden which only benefits a small number of users.

If the mulit-server route is something that would be beneficial to many users, I'd probably rather that the template be modified to support the default VPC. Or, a stack deployed to create a VPC, and then n stacks deployed. One for each new Factorio server.

I think those scripts to update the save / delete the EFS stack could be useful though, if you would like to submit a separate PR for those?

**Comment by m-chandler** [comment]
Also, happy merge in a link to your repo for the multi-server stacks.

**Comment by robertmassaioli** [comment]
That's fine, I can maintain my own fork, but to be clear, they are all auto-generated: see the generate-all.bash script.

> I think those scripts to update the save / delete the EFS stack could be useful though, if you would like to submit a separate PR for those?

Yep, I'll happily raise a PR for those. :)

**Comment by robertmassaioli** [comment]
> Also, happy merge in a link to your repo for the multi-server stacks.

Great! Let's do that then. :)

**Comment by robertmassaioli** [comment]
Done: https://github.com/m-chandler/factorio-spot-pricing/pull/37

Closing this PR now.

**Pull request closed without merging**
